### ISSUE TITLE
Opening images on click - support request

### ISSUE THREAD

**Issue by ricir** [JakeSteam/minimaJake#2]
If I'm not wrong minimaJake should open images in full-size in a new tab on click. I saw this feature on https://blog.jakelee.co.uk for instance.

However on my blog this is working only for the header image. What should I check to make it work?

**Comment by JakeSteam** [comment]
This isn't specific to the theme, and generally depends on how images are defined in your posts. For example, I typically use:

```
[![](/assets/images/my-image-thumbnail.png)](/assets/images/my-image-fullsize.png)
```

What this does is embed an image AND make it a link to a fullsize image ([another example](https://meta.stackexchange.com/a/38917/391940)). You can use the same image for both.
