### ISSUE TITLE
Icon before title (not an issue)

### ISSUE THREAD

**Issue by ricir** [JakeSteam/minimaJake#4]
Sorry if this could be misplaced, it is not an issue but a support request.
I would like to add an icon before the title in my minimaJake blog. I found a method for minima and tried to apply it to minimaJake, but I do not know if it is reliable. Moreover,   the icon appears **after**   the title (and before on mobile).

In _includes/header.html I added the following:
```
<a class="logo" href="/">
	<img src="/assets/Logo.png" alt="logo" width="30px" height="30px" /> 
</a>
```
before `<a class="site-title" rel="author" href="{{ "/" | relative_url }}">{{ site.title | escape }}</a>`

Could you suggest the good method? (Or perhaps add a new feature?)

**Comment by JakeSteam** [comment]
Hmm, I haven't tried this I'll be honest. What happens if you just put the `<img src=...` inside the `site-title` `<a` tag? 

If this doesn't work, I'll take a look!

**Comment by ricir** [comment]
It's working, ok!
`<a class="site-title" rel="author" href="{{ "/" | relative_url }}"><img src="/assets/Logo.png" alt="logo" width="30px" height="30px" />{{ site.title | escape }}</a>`

**Comment by JakeSteam** [comment]
Great! 🙂
