### ISSUE TITLE
A question about footer.html and Jekyll version

### ISSUE THREAD

**Issue by ricir** [JakeSteam/minimaJake#5]
Currently the Jekyll version in **footer.html** is obtained as follows:

`  <a href="https://jekyllrb.com/">Jekyll</a> {{ site.github.versions.jekyll | default: 1.0 }},`

When building my website I always obtain Jekyll 1.0 (site.github.versions.jekyll gives null).

Using instead the following tag I obtain the correct version:

`<a href="https://jekyllrb.com/">Jekyll</a> {{ jekyll.version | default: 1.0}},`

I suppose the current tag is for websites hosted on github, is it? If so, could you consider the possibility to add also jekyll.version tag  for websites not hosted on github?

Tks

**Comment by JakeSteam** [comment]
Hey! Good idea, I'll make it support both in the next release, thanks.

**Comment by JakeSteam** [comment]
Hey, completely forgot about this, sorry for the massive delay!

v1.0.13 now works as expected when not using GitHub Pages, hiding the "GH Pages" section and loading the correct Jekyll version:

|         GitHub Pages         |        Everywhere else        |
| :--------------------------: | :--------------------------: |
| ![](https://minima.jakelee.co.uk/images/v1_0_13_old.png) | ![](https://minima.jakelee.co.uk/images/v1_0_13_new.png) |

**Comment by ricir** [comment]
Implemented, works perfectly. 
Just a small question How could I add a CC license at the bottom of the page without  modifying the standard footer?

**Comment by JakeSteam** [comment]
Tbh I think just overriding [`footer.html`](https://github.com/JakeSteam/minimaJake/blob/main/_includes/footer.html) (by putting your own copy in the same location) would be the simplest solution. Alternatively you could just add the license to the repo your site is run from?

**Comment by ricir** [comment]
> Tbh I think just overriding [`footer.html`](https://github.com/JakeSteam/minimaJake/blob/main/_includes/footer.html) (by putting your own copy in the same location) would be the simplest solution. Alternatively you could just add the license to the repo your site is run from?

OK I'll override footer.html, tks
