### ISSUE TITLE
paginator v2

### ISSUE THREAD

**Issue by ricir** [JakeSteam/minimaJake#6]
Could you consider upgrading to [paginate-v2](https://github.com/sverrirs/jekyll-paginate-v2) ?

I understand it is not a minor change but it would allow using categories to organize posts.

**Comment by JakeSteam** [comment]
Unfortunately no, I'm intending for this theme to be compatible with GitHub pages, and that plugin is not supported.

**Comment by ricir** [comment]
I would like to add categories to my site, actually very simple ones (only 3 of them, as it is a blog on technology I would like to filter "basic" articles, "expert" articles, and "all", i.e. "no filter").  I obtained a filtering by modifying home.html, but the pagination is based on the full list and does not work for the filtered pages.

**Comment by JakeSteam** [comment]
Completely understand the requirement, I actually have multiple sites for a similar purpose (e.g. [technical articles](https://blog.jakelee.co.uk), [internet history](https://history.jakelee.co.uk), [etc](https://jakelee.co.uk))!

As a possible solution, you might want to consider customising [the search](https://github.com/JakeSteam/minimaJake/blob/main/_includes/custom/search.html) to support some sort of category filter? It might also be possible to add pagination there, I'm not sure.
